name: onboarding_form
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoLight.png"
  web:
    generate: true
    image_path: "assets/images/logoLight.png"
    background_color: "#hexcode"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/logoLight.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logoLight.png"

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  flutter_launcher_icons: ^0.13.1
  cloud_firestore: ^4.17.3
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/