// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVleKvfWlf1RRPKK7eC02oLIYO4Axwh4A',
    appId: '1:271446443741:web:b93cca751a14aa0a323d34',
    messagingSenderId: '271446443741',
    projectId: 'geniussearchonboardingform',
    authDomain: 'geniussearchonboardingform.firebaseapp.com',
    storageBucket: 'geniussearchonboardingform.appspot.com',
    measurementId: 'G-PX9SKXKQJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB5N2WD2OJsoAvcvpFGpOYy7Q7YIpdThk',
    appId: '1:271446443741:android:d3a03f4ca5d5397a323d34',
    messagingSenderId: '271446443741',
    projectId: 'geniussearchonboardingform',
    storageBucket: 'geniussearchonboardingform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEQoYRh-w42iASX9zqv-n7PX9xpTo7Loc',
    appId: '1:271446443741:ios:1613ec72982324b3323d34',
    messagingSenderId: '271446443741',
    projectId: 'geniussearchonboardingform',
    storageBucket: 'geniussearchonboardingform.appspot.com',
    iosBundleId: 'com.example.onbordingForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEQoYRh-w42iASX9zqv-n7PX9xpTo7Loc',
    appId: '1:271446443741:ios:1613ec72982324b3323d34',
    messagingSenderId: '271446443741',
    projectId: 'geniussearchonboardingform',
    storageBucket: 'geniussearchonboardingform.appspot.com',
    iosBundleId: 'com.example.onbordingForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVleKvfWlf1RRPKK7eC02oLIYO4Axwh4A',
    appId: '1:271446443741:web:21ba47a14bbdadab323d34',
    messagingSenderId: '271446443741',
    projectId: 'geniussearchonboardingform',
    authDomain: 'geniussearchonboardingform.firebaseapp.com',
    storageBucket: 'geniussearchonboardingform.appspot.com',
    measurementId: 'G-NVTRJR3ZVR',
  );
}
